-- 0001_core: reference data, people and the newsroom.
--
-- Phase 1a of docs/IMPLEMENTATION_PLAN.md. This migration creates only what the
-- public portal needs, plus the identity anchor (`users`) that Phase 1b builds
-- authentication on. Nothing financial is created here: money columns must be
-- integer minor units with an explicit currency from their first migration
-- (docs/DECISIONS.md D-003), and that belongs with the ledger, not here.
--
-- Conventions used throughout:
--   * Surrogate keys are UUID v4, generated by the database.
--   * Every table carries created_at; mutable tables carry updated_at.
--   * Text that appears in a URL is a slug, constrained by CHECK to the
--     lowercase-hyphen form. Route parameters are therefore validated by the
--     database, not only by the application.
--   * Foreign keys state their delete behaviour explicitly. Editorial content
--     is never silently destroyed by a parent delete (docs/THREAT_MODEL.md
--     T-11); RESTRICT is the default and cascade is opt-in.

-- gen_random_uuid() is core PostgreSQL from version 13 onward, so no extension
-- is required. Depending on pgcrypto here would add a privileged install step
-- to every environment for a function the server already has.

-- ---------------------------------------------------------------- reference

CREATE TABLE currencies (
    code        char(3) PRIMARY KEY,
    name        text    NOT NULL,
    -- Digits after the decimal point. 2 for INR and USD, 0 for JPY. Amounts are
    -- stored as integers in the minor unit, so this is what makes a stored
    -- 250000 mean 2,500.00 in one currency and 250,000 in another.
    minor_unit  smallint NOT NULL CHECK (minor_unit BETWEEN 0 AND 4),
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT currencies_code_upper CHECK (code = upper(code))
);

CREATE TABLE languages (
    code        text PRIMARY KEY CHECK (code ~ '^[a-z]{2}(-[A-Za-z0-9]+)*$'),
    name        text NOT NULL,
    -- Right-to-left scripts change layout, not just strings (§35).
    rtl         boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE countries (
    code              char(2) PRIMARY KEY,
    name              text    NOT NULL,
    currency_code     char(3) NOT NULL REFERENCES currencies (code) ON DELETE RESTRICT,
    default_language  text    NOT NULL REFERENCES languages  (code) ON DELETE RESTRICT,
    -- Country rules activate independently of the code being deployed (§34).
    active            boolean NOT NULL DEFAULT false,
    created_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT countries_code_upper CHECK (code = upper(code))
);

CREATE TABLE states (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    country_code  char(2) NOT NULL REFERENCES countries (code) ON DELETE RESTRICT,
    slug          text    NOT NULL CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    name          text    NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),

    UNIQUE (country_code, slug)
);

-- City slugs are globally unique because they are a top-level route
-- (/city/mumbai). Scoping them per country would require the route to carry a
-- country segment, which is a product decision, not a schema one.
CREATE TABLE cities (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug            text    NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    name            text    NOT NULL,
    -- "My Mumbai" -- the city newsroom label (§33).
    newsroom_label  text    NOT NULL,
    country_code    char(2) NOT NULL REFERENCES countries (code) ON DELETE RESTRICT,
    state_id        uuid        REFERENCES states (id) ON DELETE SET NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX cities_country_idx ON cities (country_code);

-- ------------------------------------------------------------------ people

CREATE TYPE user_status AS ENUM ('PENDING', 'ACTIVE', 'SUSPENDED', 'CLOSED');

CREATE TABLE users (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Addresses are compared case-insensitively. Storing the normalised form
    -- and constraining it is simpler to reason about than a citext column, and
    -- keeps the original out of the uniqueness decision entirely.
    email         text NOT NULL UNIQUE CHECK (email = lower(email) AND email LIKE '%@%'),
    display_name  text NOT NULL CHECK (length(btrim(display_name)) > 0),
    status        user_status NOT NULL DEFAULT 'PENDING',
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TYPE reporter_tier AS ENUM (
    'Citizen Contributor',
    'Verified Reporter',
    'Bronze',
    'Silver',
    'Gold',
    'Senior',
    'Elite',
    'Global Correspondent'
);

CREATE TABLE reporters (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    -- One reporter profile per account. A reporter is a role a user holds, not
    -- a separate identity.
    user_id     uuid NOT NULL UNIQUE REFERENCES users (id) ON DELETE RESTRICT,
    slug        text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    name        text NOT NULL,
    tier        reporter_tier NOT NULL DEFAULT 'Citizen Contributor',
    verified    boolean NOT NULL DEFAULT false,
    city_id     uuid REFERENCES cities (id) ON DELETE SET NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE reporter_languages (
    reporter_id    uuid NOT NULL REFERENCES reporters (id) ON DELETE CASCADE,
    language_code  text NOT NULL REFERENCES languages (code) ON DELETE RESTRICT,

    PRIMARY KEY (reporter_id, language_code)
);

-- --------------------------------------------------------------- newsroom

CREATE TABLE categories (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug        text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    name        text NOT NULL,
    blurb       text NOT NULL DEFAULT '',
    sort_order  integer NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- The editorial state machine of §59. A story moves through review; it is never
-- deleted, and a correction preserves what was published.
CREATE TYPE news_status AS ENUM (
    'DRAFT',
    'SUBMITTED',
    'AI_REVIEW',
    'EDITOR_REVIEW',
    'FACT_CHECK',
    'APPROVED',
    'SCHEDULED',
    'PUBLISHED',
    'CORRECTION_REQUIRED',
    'UNPUBLISHED',
    'REJECTED'
);

CREATE TABLE news (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug          text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),

    category_id   uuid NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
    -- Global stories have no city. Deleting a city must not delete its
    -- coverage, so the reference is cleared rather than cascaded.
    city_id       uuid          REFERENCES cities     (id) ON DELETE SET NULL,
    reporter_id   uuid NOT NULL REFERENCES reporters  (id) ON DELETE RESTRICT,

    kicker        text NOT NULL DEFAULT '',
    title         text NOT NULL CHECK (length(btrim(title)) > 0),
    standfirst    text NOT NULL DEFAULT '',

    status        news_status NOT NULL DEFAULT 'DRAFT',
    -- Set when the story reaches PUBLISHED. The partial index below relies on
    -- this being NULL until then.
    published_at  timestamptz,

    read_minutes  integer NOT NULL DEFAULT 1 CHECK (read_minutes > 0),
    view_count    bigint  NOT NULL DEFAULT 0 CHECK (view_count >= 0),

    breaking      boolean NOT NULL DEFAULT false,
    live          boolean NOT NULL DEFAULT false,
    -- How many independent sources a live hub aggregates (§27).
    source_count  integer NOT NULL DEFAULT 0 CHECK (source_count >= 0),

    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),

    -- A published story must carry a publication time, and an unpublished one
    -- must not claim one. Enforced here so no code path can produce a story
    -- that is published according to one column and not the other.
    CONSTRAINT news_published_has_timestamp CHECK (
        (status = 'PUBLISHED' AND published_at IS NOT NULL)
        OR (status <> 'PUBLISHED' AND published_at IS NULL)
    )
);

-- The feed query: published stories, newest first. Partial, because drafts are
-- never in a feed and there will eventually be far more of them than stories.
CREATE INDEX news_published_idx
    ON news (published_at DESC, id DESC)
    WHERE status = 'PUBLISHED';

CREATE INDEX news_category_published_idx
    ON news (category_id, published_at DESC, id DESC)
    WHERE status = 'PUBLISHED';

CREATE INDEX news_city_published_idx
    ON news (city_id, published_at DESC, id DESC)
    WHERE status = 'PUBLISHED' AND city_id IS NOT NULL;

CREATE INDEX news_reporter_idx ON news (reporter_id);

-- The ticker: breaking and live stories (§28).
CREATE INDEX news_urgent_idx
    ON news (published_at DESC, id DESC)
    WHERE status = 'PUBLISHED' AND (breaking OR live);

-- Editorial queues filter by state.
CREATE INDEX news_status_idx ON news (status, updated_at DESC);

-- Every edit is a new version. Nothing here is ever updated or deleted: a
-- correction appends (§59). Enforced by the trigger at the end of this file.
CREATE TABLE news_versions (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    news_id       uuid NOT NULL REFERENCES news (id) ON DELETE RESTRICT,
    version       integer NOT NULL CHECK (version > 0),

    title         text NOT NULL,
    standfirst    text NOT NULL DEFAULT '',
    -- Paragraphs, as text. Never markup: bodies are rendered as text nodes and
    -- the linter forbids raw HTML injection (docs/TESTING.md).
    body          text[] NOT NULL CHECK (cardinality(body) > 0),

    status        news_status NOT NULL,
    -- The account that produced this version. RESTRICT: an editor's account
    -- cannot be removed in a way that orphans the record of what they changed.
    author_id     uuid REFERENCES users (id) ON DELETE RESTRICT,
    note          text NOT NULL DEFAULT '',
    created_at    timestamptz NOT NULL DEFAULT now(),

    UNIQUE (news_id, version)
);

CREATE INDEX news_versions_news_idx ON news_versions (news_id, version DESC);

CREATE TYPE media_kind AS ENUM ('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT');

CREATE TABLE news_media (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    news_id      uuid NOT NULL REFERENCES news (id) ON DELETE CASCADE,
    kind         media_kind NOT NULL,
    -- A storage key, not a public URL. Media is served through signed URLs
    -- (§74, docs/THREAT_MODEL.md T-06), so the location must not be a
    -- ready-made public link sitting in the database.
    storage_key  text NOT NULL,
    caption      text NOT NULL DEFAULT '',
    alt_text     text NOT NULL DEFAULT '',
    sort_order   integer NOT NULL DEFAULT 0,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX news_media_news_idx ON news_media (news_id, sort_order);

-- ------------------------------------------------------- append-only guard

-- news_versions is the editorial history. If it can be updated or deleted, it
-- is not a history. The guard lives in the database so that an application bug,
-- an ad-hoc script or a future ORM cannot bypass it.
CREATE FUNCTION reject_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION
        '% is append-only; % is not permitted (see docs/DECISIONS.md)',
        TG_TABLE_NAME, TG_OP;
END;
$$;

CREATE TRIGGER news_versions_no_update
    BEFORE UPDATE ON news_versions
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE TRIGGER news_versions_no_delete
    BEFORE DELETE ON news_versions
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

-- ------------------------------------------------------------ updated_at

CREATE FUNCTION touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER users_touch     BEFORE UPDATE ON users     FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER reporters_touch BEFORE UPDATE ON reporters FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER news_touch      BEFORE UPDATE ON news      FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
